### ISSUE TITLE
Shipping symbols for Forge libraries

### ISSUE THREAD

**Issue by imradhakrishnan** [microsoft/Forge#17]
Today in Forge nuget package, we don't have symbols for the dll's and exe's. We are also not able to look them up in public symbol servers. Having symbols would help us in debugging Forge libraries as well.

**Comment by TravisOnGit** [comment]
Added symbols support in this recent PR: https://github.com/microsoft/Forge/pull/40
The NuGet package now ships with the pdb next to the dll.
