### ISSUE TITLE
Casting ActionResponse Output object to custom types in Forge schema

### ISSUE THREAD

**Issue by kijujjav** [microsoft/Forge#31]
I am trying to send a dictionary as output in ActionResponse and here are two examples

1.	new ActionResponse { StatusCode = 0, Status = false.ToString(), Output = JsonConvert.SerializeObject(outputDict) }

Forge : "ShouldSelect": "C#|UserContext.DeSerializeStringToObject((string)Session.GetLastActionResponse().Output)[\"nssLifeCycleCheck\"] == \"False\""

public Dictionary<string, string> DeSerializeStringToObject(string output)
{
            return JsonConvert.DeserializeObject<Dictionary<string, string>>(output);
}

This is working fine

2.	new ActionResponse { StatusCode = 0, Status = false.ToString(), Output = JsonConvert.SerializeObject(outputDict) }

Forge : "ShouldSelect": "C#|UserContext.DeSerializeStringToObject< Dictionary<string, string>>(>((string)Session.GetLastActionResponse().Output)[\"nssLifeCycleCheck\"] == \"False\""

public T DeSerializeStringToObject<T>(string output)
{
            return JsonConvert.DeserializeObject<T>(output);
}

This is not working.

The only difference I see between the two examples is that Instead of using generic Deserialization, In the first example I am doing specific de-serialization to Dictionary<string, string> type. What am I missing here.

Also, Please let me know if there is a way I can send Dictionary directly in output and use it on Forge, I tried the below and getting exception.

"ShouldSelect": "C#|((JObject)Session.GetLastActionResponse().Output).ToObject<Dictionary<string, string>>()[\"nssLifeCycleCheck\"] == \"true\"",

"ShouldSelect": "C#|((Dictionary<string, string>)Session.GetLastActionResponse().Output)[\"nssLifeCycleCheck\"] == \"False\"",

**Comment by TravisOnGit** [comment]
Hey kijujjav, thanks for your question!

What is your implementation of IForgeDictionary? How you are setting and getting state from this dictionary will dictate what (if any) serialization is required.

If you are using the ForgeDictionary implementation, you don’t even need to serialize and deserialize the data. You can set the ActionResponse.Output as your Dictionary<string, string>, then use it directly in the schema (after casting).

One additional thing you’ll need to do when casting is use the fully qualified name. e.g. **System.Collections.Generic.Dictionary<string,string>**. I’m not entirely sure why this is required, but Roslyn is unable to find Dictionary<,> Type for some reason.

•	Option using fully qualified name with ActionResponse.Output = Dictionary<string, string>:

```cs
return new ActionResponse { Output = new Dictionary<string, string> { { "key1", "value1" } } };
```
```
"C#|((System.Collections.Generic.Dictionary<string, string>)Session.GetLastActionResponse().Output)[\"key1\"] == \"value1\""
```

•	If you don’t like writing out the fully qualified name, here’s another option. Add a method to UserContext to cast for you.

```cs
    public Dictionary<string, string> CastDictionary(object output)
    {
        return (Dictionary<string, string>)output;
    }
```
```
"C#|UserContext.CastDictionary(Session.GetLastActionResponse().Output)[\"key1\"] == \"value1\""
```

•	If you want to cast generically, then you can do that as well. Try out this implementation:

```cs
    public T Cast<T>(object obj)
    {
        if (obj is JObject)
        {
            return ((JObject)obj).ToObject<T>();
        }

        if (obj is T)
        {
            return (T)obj;
        }

        string s = JsonConvert.SerializeObject(obj);
        return JsonConvert.DeserializeObject<T>(s);
    }
```
```
"C#|UserContext.Cast<System.Collections.Generic.Dictionary<string, string>>(Session.GetLastActionResponse().Output)[\"key1\"] == \"value1\""
```

•	The generic cast works for other objects as well. If your ActionResponse was a custom object containing a Dictionary, you could retrieve the data like this:

```
"ShouldSelect": "C#|UserContext.Cast<MyCustomOutput>(Session.GetLastActionResponse().Output).Dict[\"key1\"] == \"value1\"",
```

Let me know if you have any follow-up questions.
Thanks,
--Travis

**Comment by TravisOnGit** [comment]
Closing issue. Please re-open if you have any follow-up questions.
