### ISSUE TITLE
Migrate to NetStandard 2.0

### ISSUE THREAD

**Issue by geffzhang** [microsoft/Forge#36]
This library is .NET framework 4.6.2, is there a plan to migrate to NetStandard 2.0, convenient for use on .NET Core 3.1

**Comment by TravisOnGit** [comment]
We are tied to 4.6.2 because of Roslyn dependencies. If Roslyn is supported in .NET Core, it would be nice to support standard and core. No short-term plans to support .NET Core, but it could happen down the road.

**Comment by TravisOnGit** [comment]
NetStandard 2.0 is now supported from version 1.0.57.
