### ISSUE TITLE
Does Forge expose any API to validate schemas

### ISSUE THREAD

**Issue by kijujjav** [microsoft/Forge#37]
I see that in unit test proj, contracts\\ForgeSchemaValidationRules.json is used to validate the schema, similarly is there a public API that users can make use of to validate schemas?

**Comment by TravisOnGit** [comment]
No, but that's a good idea. Turning this into a feature request.

**Comment by kijujjav** [comment]
@TravisOnGit , Is this feature committed yet?

**Comment by codemonkeyhhq** [comment]
> @TravisOnGit , Is this feature committed yet?
@kijujjav Hi Kiran, thank you for bring this idea up. I have implemented this feature with the guide of Travis and please check out this [Pull request](https://github.com/microsoft/Forge/pull/44)

**Comment by TravisOnGit** [comment]
This PR has been checked in and a new ForgeSchemaValidator static class is available in version 1.0.59. Thanks for your suggestion!

https://github.com/microsoft/Forge/pull/44
