### ISSUE TITLE
EvaluateDynamicProperty inconsistent behavior for version 1.0.55 [Bug]

### ISSUE THREAD

**Issue by swbae31** [microsoft/Forge#39]
I bumped up Forge version from 1.0.52 to 1.0.55 and I'm getting EvaluateDynamicProperty failed to parse schemaObj errors that was not happening before. 

**Error**
```
EvaluateDynamicProperty failed to parse schemaObj: {
  "UserParameters": "C#|UserContext.GetUserParameters()"
}, knownType: Microsoft.Azure.Solutions.TroubleshooterV2Library.WorkflowEngine.Forge.ForgeActions.DataInput.
```

**Action Input within Schema:**
```
"Input": {
          "UserParameters": "C#|UserContext.GetUserParameters()"
}
```

**Input Data Model**
```
public class DataInput
{
      public Dictionary<string, string> UserParameters { get; set; }
}
```

**User Context which has the function GetUserParameters()**
```
public Dictionary<string, string> GetUserParameters()
 {
            return this.userParameters;
 }
```

I am sure that I have my Forge set up correct because everything worked as expected in version 1.0.52. Has something changed with EvaluateDynamicProperty 1.0.55 that I do not know? Or is this a bug with 1.0.55

**Comment by swbae31** [comment]
Issue caused by trying to use Forge on .net Core 2.2 (.NET Framework compatibility mode). Mismatch in CodeAnalysis frameworks (Roslyn) caused references not to be resolved throwing non implemented exception from the memory changes after 1.0.52 version. Closing issue.

**Comment by TravisOnGit** [comment]
Added NetStandard 2.0 support to Forge in this PR: https://github.com/microsoft/Forge/pull/40
Added workaround for MissingResolver issue for NetStandard in this PR: https://github.com/microsoft/Forge/pull/41
Tested offline with swbae31 to confirm this resolves the issue and unblocks them to upgrade to latest Forge version.
