### ISSUE TITLE
What is the current status of Forge and ForgeEditor?

### ISSUE THREAD

**Issue by stevesimmons** [microsoft/Forge#47]
Can you please explain the current status of Forge within Microsoft? It looks an interesting project (internal tool). However of limited utility without the ForgeEditor graphical editor tool.

The apparent promise in README.md to open ForgeEditor by the end of 2019 became "coming soon" in Jan 2020. We are now nearing the end of 2021 and it hasn't appeared.

Does this imply Forge is no longer actively positioned for use outside MS?

**Comment by TravisOnGit** [comment]
Hey Steve,

Thanks for reaching out. Forge continues to be used by new services inside of Microsoft, and has helped them successfully launch into production. Forge is well positioned to be supported for the foreseeable future, as several critical and customer-facing services rely on it. We've also had some new contributors this semester, which is great to see, and helps the longevity of the project.

Regarding ForgeEditor. ForgeEditor is a useful tool for visualizing the tree. It can help edit the tree, but the features are still lacking a bit here, and manually updating the JSON is still required. What I'm saying is that you can successfully use Forge without the ForgeEditor.

In the past couple months, a new team has formed that has ForgeEditor in their charter/responsibilities. I reached out about ForgeEditor GitHub plans, and they said they will consider it in next semester's planning, around Feb/March. The long-term plan is still to open source the ForgeEditor as well. But understandable, it can be difficult to prioritize it over other work.

I asked if it would be possible to put out an exe of the current version of ForgeEditor before the move to GitHub. I'll follow up here when I get a response. This would hopefully hold over external folks well enough until the full GitHub release. Let me know if this is something you would be interested in, as external pressure helps prioritize the work :)

Thanks,
--Travis

**Comment by TravisOnGit** [comment]
Update:
A blocker for putting out a public exe of ForgeEditor is upgrading some older dependencies with vulnerabilities. This proved to be non-trivial. The team plans to give this another try after completing some higher priority work. Planning for first half of 2022.

ForgeEditor on GitHub, as I mentioned previously, will be considered next planning cycle (Feb/March), but is not guaranteed. Perhaps it could be a nice intern project. This could potentially land sometime later in 2022.

Closing out this Issue, but feel free to re-open if you have any follow-ups. Thanks!
